name: "Setup Go Environment"
description: "Sets up Go and installs dependencies"
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Install Dependencies
      run: go mod tidy

    - name: Add Go Tools to PATH
      run: echo "$HOME/go/bin" >> $GITHUB_PATH