name: Weather App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: 'true' # To speed up builds by caching dependencies

      - name: Install Dependencies
        run: go mod tidy

      - name: Add Go Tools to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build Binary
        run: go build -o weather-cli

      - name: Run Static Analysis
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Run Unit Tests
        run: go test -v ./...
